# Listner Configuration
http:
  host: "0.0.0.0"
  port: "8081"
  basePath: "api/*"
  
# Api Configuration
api:
  id: "18625930"  

# Salesforce Configuration
sfdc:
 Token: "![dliD83aSLqnGEFpUsLLG1KRvlXjSUYhm9dGUROKQ8b8=]"
 password: "![JxqS30efTx6nQMUoPYd3QQ==]"
 UserName: "![GfpArQYa08tjNFO3Oo+veC03m6Orr5xW6vXP0Jge0UM=]"